[github_app]
pr_commands = [
    "/describe",
    "/review",
    "/improve",
    "/update_changelog",  
]



[pr_find_similar_component]
search_from_org = true 
number_of_keywords = 5  
number_of_results = 5  

[pr_description]
extra_instructions="""\
1. For the title, use the format [type]: [summary] do an estimate of the level of effort for the PR and add the the estimate between 1-10.
2. In the body of the description generate 1 Mermaid Diagram Class Diagram that describes the code that has been changed, this diagram must be placed after all the other contents of the description.

Mermaid Diagram Class Diagram Instructions when creating Mermaid diagrams, follow these guidelines:
1. Always use proper code blocks: Every Mermaid diagram MUST be surrounded by a code block with the mermaid language identifier
2. Required format: The opening line must be exactly three backticks followed immediately by the word mermaid (no spaces between backticks and mermaid), and the closing line must be exactly three backticks
3. The mermaid code must start on the line immediately after the opening three backticks and mermaid
4. Common mistakes to avoid:
   - Do NOT write Mermaid code without the code block
   - Do NOT use angle bracket tags or any other format
   - Do NOT forget to specify mermaid as the language identifier after the three backticks
   - Do NOT include any text or comments outside the code block
   - Do NOT put the mermaid diagram at the beginning - it must come after all other description content

Remember: The code block with three backticks followed by mermaid is mandatory for proper rendering. Without it, the diagram will appear as plain text and won't be processed correctly.

"""
publish_labels=true
generate_ai_title=true

[pr_code_suggestions]
extra_instructions="""\
Additional instructions:
-For every GraphQl Query's names, always include the word For in the name.
"""
num_code_suggestions_per_chunk="8"
suggestions_score_threshold="8"
ask_for_confirmation = true
demand_code_suggestions_self_review = true
allow_thumbs_up_down = true
enable_chat_in_code_suggestions = true

[config]
publish_logs=false



[rag_arguments]
enable_rag=true
rag_repo_list = ["Codium-ai/devlabs"]

[pr_update_changelog]
push_changelog_changes = true
