[github_app]
pr_commands = [ "/improve"
]

[pr_code_suggestions]
extra_instructions="""\
Additional instructions:
- When reviewing GraphQL queries, if the query name does not contain 'For', provide a suggestion to rename the query to include 'For' for consistency.
"""
num_code_suggestions_per_chunk="8"
suggestions_score_threshold="8"
ask_for_confirmation = true
demand_code_suggestions_self_review = true
allow_thumbs_up_down = true
enable_chat_in_code_suggestions = true

# Custom rule for GraphQL query naming
[graphql_query_naming]
enabled = true
rule = "If a GraphQL query name does not contain 'For', suggest renaming it to include 'For'."
